auth:
  client-id: client_1
  secret: 123456

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC
    hikari:
      username: root
      password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
jpa:
  show-sql: true